routes/web.php
<?php

use App\Http\Controllers\Admin\ManageUserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Admin\TodoController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home',function(){
    // return "Hello Test";
    return view('front.home');
});

Route::get('/about',function(){
    // return "Hello Test";
    return view('front.about');
});

// Route::get('/students',[StudentController::class,'index'])->name('students.index');
// Route::resource('categories', CategoryController::class);



Auth::routes();


Route::group(['prefix' => 'admin','middleware' => 'auth'], function()
{
    //All the routes that belongs to the group goes here
    Route::get('/hello', function() {
        return "Hello Dashboard";
    } );

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
    Route::resource('/todos',TodoController::class);
    Route::resource('/students',StudentController::class);
    Route::resource('/classes',ClassController::class);

    // Users
    Route::resource('/users', ManageUserController::class);


});
















// Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['web', 'auth','isAdmin']], function () {
//     // Route::get('/', [DashboardController::class, 'Dashboard'])->name('dashboard');
//     Route::resources([
//         'classes' => 'App\Http\Controllers\Admin\ClassesController',
//         // 'post' => 'App\Http\Controllers\Admin\PostController',
//         // 'tag' => 'App\Http\Controllers\Admin\TagController',
//         // 'user' => 'App\Http\Controllers\Admin\UserController',
//         // 'comment' => 'App\Http\Controllers\Admin\CommentController'
//     ]);
// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
    protected $table="students";
    protected $fillable=([
        'name','sex','dob','address','profile','class_id','user_id','status'
    ]);
}

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Classes;
use App\Models\Student;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $data=[];
        $data['students']=Student::get();

        // return $data['students'];
        return view('admin.students.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data=[];
        $data['classes']=Classes::get();

        return view('admin.students.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request;
        Student::create([
            'name' =>$request->name,
            'sex'  =>$request->sex,
            'dob'   =>$request->dob,
            'address' =>$request->address,
            'status'    => $request->status,
            'class_id'  =>$request->class_id,
            'user_id'   => Auth::user()->id
        ]);

        return redirect('admin/students')->with('success',"Save Student success!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $data=[];
       $data['student']=Student::findOrFail($id);

       return view('admin.students.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=[];

        $data['classes']=Classes::get();
       $data['student']=Student::findOrFail($id);

       return view('admin.students.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // return $request;

        $student=Student::findOrFail($id);
        $student->update([
            'name'  =>$request->name,
            'sex'   =>$request->sex,
            'status' =>$request->status,
        ]);

        return redirect('admin/students');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Student::find($id)->delete($id);

        return response()->json([
            'success' => 'Record deleted successfully!'
        ]);

    }
}

resources/views/admin/students/create.blade.php
@extends('layouts.admin')
@section('title','Create Class')
@push('css')

@endpush
@section('content')
            <form method="POST" action="{{route('students.store')}}">
                @csrf
                <div class="card">
                    <div class="card-header"><h4>{{'Create Student'}} <span class="float-right"></h4> </div>
                            <div class="container">

                               <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label for="name">Student Name:</label>
                                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter Class Name" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="sel1">Gender:</label>
                                            <select class="form-control" id="sel1" name="sex">
                                                <option value="Male">Male</option>
                                                <option value="Female">Female</option>

                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label for="dob">Date of Birth:</label>
                                            <input type="date" class="form-control" id="dob" name="dob" placeholder="Enter Sort" required>
                                        </div>

                                        <div class="form-group">
                                            <label for="sel1">Class:</label>
                                            <select class="form-control" id="sel1" name="class_id">
                                                @foreach ($classes as $class)
                                                    <option value="{{$class->id}}">{{$class->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="address">Address:</label>
                                            <input type="text" class="form-control" id="address" name="address" placeholder="Enter Address ex.Siem Reap" required>
                                        </div>

                                        <div class="form-group">
                                            <label for="sel1">Status:</label>
                                            <select class="form-control" id="sel1" name="status">
                                                <option value="1">Active</option>
                                                <option value="0">Not Active</option>

                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                            {{-- {!! Form::file($name, [$options]) !!} --}}
                                            <input type="file" class="btn btn-primary" name="profile" id="" style="width: 100%;">
                                            {{-- <button type="submit" class="btn btn-primary">Brow</button> --}}
                                    </div>
                               </div>

                            </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-danger float-right" href="{{url('/admin/classes')}}">Cancel</a>
                   </div>
               </div>

            </form>
@endsection

@push('js')

<script type="text/javascript">

</script>
@endpush

resources/views/admin/students/edit.blade.php
@extends('layouts.admin')
@section('title','Create Class')
@push('css')

@endpush
@section('content')
            <form method="POST" action="{{route('students.update',$student->id)}}" enctype="multipart/form-data">

                @csrf
                @method('PUT')

                <div class="card">
                    <div class="card-header"><h4>{{'Create Student'}} <span class="float-right"></h4> </div>
                            <div class="container">

                               <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label for="name">Student Name:</label>
                                            <input type="text" class="form-control" id="name" name="name" value="{{$student->name}}" placeholder="Enter Class Name" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="sel1">Gender:</label>
                                            <select class="form-control" id="sel1" name="sex">
                                                <option {{$student=='Male'?'selected':''}} value="Male">Male</option>
                                                <option {{$student=='Female'?'selected':''}} value="Female">Female</option>

                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label for="dob">Date of Birth:</label>
                                            <input type="date" class="form-control" id="dob" name="dob" value="{{$student->dob}}" placeholder="Enter Sort" required>
                                        </div>

                                        <div class="form-group">
                                            <label for="sel1">Class:</label>
                                            <select class="form-control" id="sel1" name="class_id">
                                                @foreach ($classes as $class)
                                                    <option {{$class->id==$student->class_id?'selected':''}} value="{{$class->id}}">{{$class->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="address">Address:</label>
                                            <input type="text" class="form-control" id="address" name="address" value="{{$student->address}}" placeholder="Enter Address ex.Siem Reap" required>
                                        </div>

                                        <div class="form-group">
                                            <label for="sel1">Status:</label>
                                            <select class="form-control" id="sel1" name="status">
                                                <option {{$student->status==1?'selected':''}} value="1">Active</option>
                                                <option {{$student->status==0?'selected':''}} value="0">Not Active</option>

                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                            {{-- {!! Form::file($name, [$options]) !!} --}}
                                            <input type="file" class="btn btn-primary" name="profile" id="" style="width: 100%;">
                                            {{-- <button type="submit" class="btn btn-primary">Brow</button> --}}
                                    </div>
                               </div>

                            </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Update</button>
                        <a class="btn btn-danger float-right" href="{{url('/admin/classes')}}">Cancel</a>
                   </div>
               </div>

            </form>
@endsection

@push('js')

<script type="text/javascript">

</script>
@endpush

resources/views/admin/students/index.blade.php
@extends('layouts.admin')
@section('title','List Student')

@push('css')

@endpush

@section('content')
    <div class="card">
        <div class="card-header"><h4>{{'Student List'}} <span class="float-right"><a class="btn btn-primary" href="{{url('admin/students/create')}}">Create</a></span></h4>
        </div>
            <table class="table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Student Name</th>
                      <th>Created at</th>
                      <th>Option</th>
                    </tr>
                  </thead>

                  <tbody>
                    @foreach ($students as $item)
                      <?php $id=($item->id%2); ?>
                      <tr class="{{$id==0?'success':''}}" >
                          <td>{{$item->id}}</td>
                          <td>
                              @if ($item->status ==1)
                                  <i class="fa fa-circle text-success"></i>
                              @else
                                  <i class="fa fa-circle text-danger"></i>
                              @endif
                              {{$item->name}}
                          </td>
                          <td>{{$item->created_at}}</td>
                          <td>
                              <a href="{{ route('students.show',$item->id) }}" class="btn btn-warning btn-sm">
                                  Show
                              </a>
                              <a href="{{ route('students.edit',$item->id) }}" class="btn btn-success btn-sm">Edit</a>
                              <button class="deleteRecord btn btn-danger btn-sm" data-id="{{ $item->id }}" >Delete</button>
                          </td>
                      </tr>
                    @endforeach

                  </tbody>
            </table>

    </div>

@endsection

@push('js')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">
   $(".deleteRecord").click(function(){
    //    alert("Hello");
    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");

    swal({
        title: "Are you sure?",
        text: "Please Check before Delete!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
        })
        .then((willDelete) => {
        if (willDelete) {
            $.ajax(
                    {
                         url: "students/"+id,
                        type: 'DELETE',
                        data: {
                            "id": id,
                            "_token": token,
                        },
                        success: function (){
                            swal("Poof! Your record has been deleted!", {
                            icon: "success",
                            });
                            window.location.href = "{{url('/admin/students')}}";
                        }
                    });
        } else {
            swal("Your record is safe!");
        }
        });
});
</script>
@endpush

resources/views/admin/students/show.blade.php
@extends('layouts.admin')
@section('title','Create Class')
@push('css')

@endpush
@section('content')
            <form method="POST" action="{{route('students.store')}}">
                {{-- @csrf
                {{ method_field('PUT') }} --}}
                <div class="card">
                    <div class="card-header"><h4>{{'Show Student'}} <span class="float-right"></h4> </div>
                            <div class="container">

                                <div class="form-group">
                                    <label for="name">Student Name:</label>
                                    <input type="text" disabled class="form-control" id="name" name="name" value="{{$student->name}}" placeholder="Enter Class Name" required>
                                </div>
                                <div class="form-group">
                                    <label for="sort">Sort:</label>
                                    <input type="text" disabled class="form-control" id="sort" name="sort" value="{{$student->sex}}" placeholder="Enter Sort" required>
                                </div>
                                <div class="form-group">
                                    <label for="sel1">Status:</label>
                                    <select disabled class="form-control" id="sel1" name="status">
                                      <option {{$student->status==1?'selected':''}} value="1">Active</option>
                                      <option {{$student->status==0?'selected':''}} value="0">Not Active</option>

                                    </select>
                                </div>

                            </div>

                    <div class="card-footer">
                        {{-- <button type="submit" class="btn btn-primary">Update</button> --}}
                        <a class="btn btn-danger float-right" href="{{url('/admin/students')}}">Cancel</a>
                   </div>
               </div>

            </form>
@endsection

@push('js')

<script type="text/javascript">

</script>
@endpush