routes/web.php
<?php

use App\Http\Controllers\Admin\ManageUserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Admin\TodoController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home',function(){
    // return "Hello Test";
    return view('front.home');
});

Route::get('/about',function(){
    // return "Hello Test";
    return view('front.about');
});

// Route::get('/students',[StudentController::class,'index'])->name('students.index');
// Route::resource('categories', CategoryController::class);



Auth::routes();


Route::group(['prefix' => 'admin','middleware' => 'auth'], function()
{
    //All the routes that belongs to the group goes here
    Route::get('/hello', function() {
        return "Hello Dashboard";
    } );

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
    Route::resource('/todos',TodoController::class);
    Route::resource('/students',StudentController::class);
    Route::resource('/classes',ClassController::class);

    // Users
    Route::resource('/users', ManageUserController::class);


});
















// Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['web', 'auth','isAdmin']], function () {
//     // Route::get('/', [DashboardController::class, 'Dashboard'])->name('dashboard');
//     Route::resources([
//         'classes' => 'App\Http\Controllers\Admin\ClassesController',
//         // 'post' => 'App\Http\Controllers\Admin\PostController',
//         // 'tag' => 'App\Http\Controllers\Admin\TagController',
//         // 'user' => 'App\Http\Controllers\Admin\UserController',
//         // 'comment' => 'App\Http\Controllers\Admin\CommentController'
//     ]);
// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    use HasFactory;
    protected $table="todos";
    protected $fillable=([
        'title','category_id','user_id'
    ]);
}

app/Http/Controllers/Admin/TodoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Todo;
use App\Models\Classes;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=[];
        $data['Todos']=Todo::get();

        return view('admin.todos.index',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data=[];
        $data['classes']=Classes::get();
        return view('admin.todos.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = [];
        // dd($request);
        foreach($request->input('title') as $key => $value) {
            $data["title.{$key}"] = 'required';
        }
        // foreach($request->input('category_id') as $key => $cat) {
        //     $data["category_id.{$key}"] = 'required';
        // }
        $cat=$request->category_id;




        $validator = Validator::make($request->all(), $data);

        if ($validator->passes()) {

            // foreach($request->input('title') as $key => $value) {
            //     Todo::create([
            //         'title'=>$value,
            //         'category_id' => 1,
            //         'user_id'   =>Auth::user()->id
            //     ]);
            // }

            foreach($request->input('title') as $key => $value) {
                Todo::create([
                    'title'=>$value,
                    'category_id' => $cat[$key],
                    'user_id'   =>Auth::user()->id
                ]);
            }

            return response()->json(['success'=>'true']);

        }

        return response()->json(['error'=>$validator->errors()->all()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Todo::find($id)->delete($id);

        return response()->json([
            'success' => 'Record deleted successfully!'
        ]);
    }
}

resources/views/admin/todos/create.blade.php
@extends('layouts.admin')
@section('title','Create Class')
@push('css')
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"></script>
@endpush
@section('content')
<form name="add_name" id="add_name">
    <div class="alert alert-danger show-error-message" style="display:none">
    <ul></ul>
    </div>
    <div class="alert alert-success show-success-message" style="display:none">
    <ul></ul>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered" id="dynamic_field">
            <tr>
                <td> <input type="text" name="title[]" placeholder="Enter title" class="form-control name_list" / id="title">
                </td>
                <td>
                    {{-- <input type="text" name="category_id[]" placeholder="Enter Category" class="form-control name_list" / id="category_id"> --}}
                    <select class="form-control" id="category_id" name="category_id[]">
                        @foreach ($classes as $class)
                            <option value="{{$class->id}}">{{$class->name}}</option>
                        @endforeach
                    </select>
                </td>
                <td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>
            </tr>
        </table>
    <input type="button" name="submit" id="submit" class="btn btn-primary" value="Submit" />
    </div>
</form>
@endsection

@push('js')

<script type="text/javascript">
    $(document).ready(function(){
        var url = "{{ url('admin/todos/create') }}";
        var i=1;
        $('#add').click(function(){
            var title = $("#title").val();
            i++;
            $('#dynamic_field').append(
                '<tr id="row'+i+'" class="dynamic-added"><td><input type="text" name="title[]" placeholder="Enter title" class="form-control name_list" value="'+title+'" /></td>  <td><select class="form-control" id="category_id" name="category_id[]">@foreach ($classes as $class) <option value="{{$class->id}}">{{$class->name}}</option>         @endforeach</select></td> <td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>'
                );


        });
        $(document).on('click', '.btn_remove', function(){
            var button_id = $(this).attr("id");
            $('#row'+button_id+'').remove();
            });
            $.ajaxSetup({
                headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#submit').click(function(){
                // alert("Save");
                $.ajax({
                        url:"{{ url('admin/todos') }}",
                        method:"POST",
                        data:$('#add_name').serialize(),
                        type:'json',
                        success:function(data)
                        {
                            if(data.error){
                                display_error_messages(data.error);
                            }else{
                                    i=1;
                                    $('.dynamic-added').remove();
                                    $('#add_name')[0].reset();
                                    $(".show-success-message").find("ul").html('');
                                    $(".show-success-message").css('display','block');
                                    $(".show-error-message").css('display','none');
                                    $(".show-success-message").find("ul").append('<li>Todos Has Been Successfully Inserted.</li>');
                                }
                        }
                });
            }); // End Submit Save

            function display_error_messages(msg) {
                    $(".show-error-message").find("ul").html('');
                    $(".show-error-message").css('display','block');
                    $(".show-success-message").css('display','none');
                    $.each( msg, function( key, value ) {
                        $(".show-error-message").find("ul").append('<li>'+value+'</li>');
                    });
                }
        });
</script>


@endpush

resources/views/admin/todos/index.blade.php
@extends('layouts.admin')
@section('title','List Classes')

@push('css')

@endpush

@section('content')
    <div class="card">
        <div class="card-header"><h4>{{'Todo List'}} <span class="float-right"><a class="btn btn-primary" href="{{url('admin/todos/create')}}">Create</a></span></h4>
        </div>
            <table class="table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Todo Title</th>
                      <th>Created at</th>
                      <th>Option</th>
                    </tr>
                  </thead>

                  <tbody>
                    @foreach ($Todos as $item)
                      <?php $id=($item->id%2); ?>
                      <tr class="{{$id==0?'success':''}}" >
                          <td>{{$item->id}}</td>
                          <td>
                              @if ($item->status ==1)
                                  <i class="fa fa-circle text-success"></i>
                              @else
                                  <i class="fa fa-circle text-danger"></i>
                              @endif
                              {{$item->title}}
                          </td>
                          <td>{{$item->created_at}}</td>
                          <td>
                              <a href="{{ route('todos.show',$item->id) }}" class="btn btn-warning btn-sm">
                                  Show
                              </a>
                              <a href="{{ route('todos.edit',$item->id) }}" class="btn btn-success btn-sm">Edit</a>
                              <button class="deleteRecord btn btn-danger btn-sm" data-id="{{ $item->id }}" >Delete</button>
                          </td>
                      </tr>
                    @endforeach

                  </tbody>
            </table>

    </div>

@endsection

@push('js')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">
   $(".deleteRecord").click(function(){
    //    alert("Hello");
    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
    // Swal.fire({
    //         title: 'Are you sure?',
    //         text: "You won't be able to revert this!",
    //         icon: 'warning',
    //         showCancelButton: true,
    //         confirmButtonColor: '#3085d6',
    //         cancelButtonColor: '#d33',
    //         confirmButtonText: 'Yes, delete it!'
    //         }).then((result) => {
    //         if (result.isConfirmed) {
    //             $.ajax(
    //                 {
    //                      url: "todos/"+id,
    //                     type: 'DELETE',
    //                     data: {
    //                         "id": id,
    //                         "_token": token,
    //                     },
    //                     success: function (){
    //                         swal("Poof! Your record has been deleted!", {
    //                         icon: "success",
    //                         });
    //                         window.location.href = "{{url('/admin/todos')}}";
    //                     }
    //                 });
    //             Swal.fire(
    //             'Deleted!',
    //             'Your file has been deleted.',
    //             'success'
    //             )
    //         }
    //         });


    swal({
        title: "Do you want to delete this?",
        text: "Please Check before Delete!",
        icon: "warning",
        confirmButtonColor: '#3085d6',
        buttons: true,
        dangerMode: true,

        })
        .then((willDelete) => {
        if (willDelete) {
            $.ajax(
                    {
                         url: "todos/"+id,
                        type: 'DELETE',
                        data: {
                            "id": id,
                            "_token": token,
                        },
                        success: function (){
                            swal("Poof! Your record has been deleted!", {
                            icon: "success",
                            });
                            window.location.href = "{{url('/admin/todos')}}";
                        }
                    });
        }
        //  else {
        //     swal("Your record is safe!");
        // }
        });
});
</script>
@endpush