routes/web.php
<?php

use App\Http\Controllers\Admin\ManageUserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Admin\TodoController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home',function(){
    // return "Hello Test";
    return view('front.home');
});

Route::get('/about',function(){
    // return "Hello Test";
    return view('front.about');
});

// Route::get('/students',[StudentController::class,'index'])->name('students.index');
// Route::resource('categories', CategoryController::class);



Auth::routes();


Route::group(['prefix' => 'admin','middleware' => 'auth'], function()
{
    //All the routes that belongs to the group goes here
    Route::get('/hello', function() {
        return "Hello Dashboard";
    } );

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
    Route::resource('/todos',TodoController::class);
    Route::resource('/students',StudentController::class);
    Route::resource('/classes',ClassController::class);

    // Users
    Route::resource('/users', ManageUserController::class);


});
















// Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['web', 'auth','isAdmin']], function () {
//     // Route::get('/', [DashboardController::class, 'Dashboard'])->name('dashboard');
//     Route::resources([
//         'classes' => 'App\Http\Controllers\Admin\ClassesController',
//         // 'post' => 'App\Http\Controllers\Admin\PostController',
//         // 'tag' => 'App\Http\Controllers\Admin\TagController',
//         // 'user' => 'App\Http\Controllers\Admin\UserController',
//         // 'comment' => 'App\Http\Controllers\Admin\CommentController'
//     ]);
// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'latin_name',
        'email',
        'password',
        'user_type',
        'photo',
        'is_active',
        'gender'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')
@section('title',$User->name)
@push('css')
    <link rel="stylesheet" href="{{asset('backend/plugins/daterangepicker/daterangepicker.css')}}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="{{asset('backend/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css')}}">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{asset('backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('backend/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="{{asset('backend/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('backend/dist/css/adminlte.min.css')}}">

@endpush


@section('content')
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">User Information</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form"  action="{{route('users.update',$User->id)}}" autocomplete="off" enctype="multipart/form-data" method="post" accept-charset="utf-8">

        @csrf
        {{ method_field('PATCH') }}

            <div class="row">
                <div class="col-md-8">
                    <div class="card-body">

                        <div class="form-group">
                            <label for="full_name">នាមត្រកូល នាមខ្លួន​</label>
                            <input type="text" class="form-control" name="name" id="full_name" placeholder="Enter Full Name" value="{{$User->name}}">
                        </div>

                        <div class="form-group">
                            <label for="full_name">Latin Name</label>
                            <input type="text" class="form-control" name="latin_name" id="full_name" placeholder="Enter Full Name" value="{{$User->latin_name}}">
                        </div>

                        <div class="form-group">
                            <label for="full_name">Gender</label>
                            <select class="custom-select" name="gender">
                                <option {{$User->gender=='M'?'selected':''}} value="M">Male</option>
                                <option {{$User->gender=='F'?'selected':''}} value="F">Female</option>

                            </select>
                        </div>




                        <div class="form-group">
                          <label for="exampleInputEmail1">Email address</label>
                          <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" value="{{$User->email}}">
                        </div>

                        <div class="form-group">
                            <label for="full_name">User Type</label>
                            <select class="custom-select" name="user_type">
                                <option {{$User->user_type=='admin'?'selected':''}} value="admin">Admin</option>
                                <option {{$User->user_type=='teacher'?'selected':''}} value="teacher">Teacher</option>
                                <option {{$User->user_type=='guest'?'selected':''}} value="guest">Guest</option>
                            </select>
                        </div>

                        <div class="form-group clearfix">

                            <div class="icheck-primary d-inline">
                              <input type="checkbox" id="checkboxPrimary3" name="is_active" {{$User->is_active==1?'checked':''}}>
                              <label for="checkboxPrimary3">
                                Active
                              </label>
                            </div>
                          </div>



                    </div>

                </div>
                <div class="col-md 4">
                    @php
                    $Profile=$User->photo!=NULL?$User->photo:'users/default.jpg';
                @endphp

                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                          <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src="{{asset('uploads/'.$Profile)}}" alt="User profile picture">
                          </div>

                          <h3 class="profile-username text-center">{{$User->name}}</h3>

                          <p class="text-muted text-center">{{$User->user_type}}</p>

                          <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                              <b>Followers</b> <a class="float-right">1,322</a>
                            </li>
                            <li class="list-group-item">
                              <b>Following</b> <a class="float-right">543</a>
                            </li>
                            <li class="list-group-item">
                              <b>Friends</b> <a class="float-right">13,287</a>
                            </li>
                          </ul>

                          <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
                        </div>
                        <!-- /.card-body -->
                      </div>
                </div>
            </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <a  class="btn btn-primary float-right" href="{{url('admin/users')}}">Back</a>
        <input type="submit" class="btn btn-success " value="Update">
      </div>
    </form>
  </div>

@endsection

@push('js')

<!-- Bootstrap 4 -->
<script src="{{asset('backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- Select2 -->
<script src="{{asset('backend/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{{asset('backend/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js')}}"></script>
<!-- InputMask -->
<script src="{{asset('backend/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('backend/plugins/inputmask/min/jquery.inputmask.bundle.min.js')}}"></script>
<!-- date-range-picker -->
<script src="{{asset('backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- bootstrap color picker -->
<script src="{{asset('backend/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Bootstrap Switch -->
<script src="{{asset('backend/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('backend/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('backend/dist/js/demo.js')}}"></script>
<!-- Page script -->
<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
        theme: 'bootstrap4'
        })

        //Datemask dd/mm/yyyy
        $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
        //Datemask2 mm/dd/yyyy
        $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
        //Money Euro
        $('[data-mask]').inputmask()

        //Date range picker
        $('#reservation').daterangepicker()
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({
        timePicker: true,
        timePickerIncrement: 30,
        locale: {
            format: 'MM/DD/YYYY hh:mm A'
        }
        })
        //Date range as a button
        $('#daterange-btn').daterangepicker(
        {
            ranges   : {
            'Today'       : [moment(), moment()],
            'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month'  : [moment().startOf('month'), moment().endOf('month')],
            'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            startDate: moment().subtract(29, 'days'),
            endDate  : moment()
        },
        function (start, end) {
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
        }
        )

        //Timepicker
        $('#timepicker').datetimepicker({
        format: 'LT'
        })

        //Bootstrap Duallistbox
        $('.duallistbox').bootstrapDualListbox()

        //Colorpicker
        $('.my-colorpicker1').colorpicker()
        //color picker with addon
        $('.my-colorpicker2').colorpicker()

        $('.my-colorpicker2').on('colorpickerChange', function(event) {
        $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
        });

        $("input[data-bootstrap-switch]").each(function(){
        $(this).bootstrapSwitch('state', $(this).prop('checked'));
        });

    })
    </script>
@endpush

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('title',"List User")

@push('css')
    {{-- Data Table Style --}}
    <link rel="stylesheet" href="{{asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')

    <div class="card">
        <div class="card-header">
        <h3 class="card-title">User List</h3> <span><a class="btn btn-primary btn-sm float-right" href="#"> Add New</a></span>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>User Type</th>
            <th>Action</th>
            </tr>
            </thead>
            <tbody>

                @foreach ($Users as $row)
                    <tr>
                        <td>
                            {{$row->id}}
                        </td>
                        <td>
                            @php
                                $profile=$row->photo!=NULL?$row->photo : 'users/default.jpg';
                            @endphp
                            <div class="user-block">
                                <img class="img-circle img-bordered-sm" src="{{asset('uploads/'. $profile )}}" alt="User Image">
                                <span class="username">
                                <a href="{{url('admin/user_profile/'.$row->id)}}">{{$row->name}}</a>
                                {{-- <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a> --}}
                                </span>
                                <span class="description">3 days ago</span>
                            </div>
                        </td>
                        <td>
                            {{$row->email}}
                        </td>

                        <td>
                            <span class="btn btn-{{$row->is_active=='1'?'success':'danger'}} btn-sm">{{$row->user_type}}</span>
                        </td>
                        <td>
                            <div class="btn-group btn-group-toggle" data-toggle="buttons">


                                <a class="btn btn-primary btn-sm active" href="{{url('admin/users/'.$row->id)}}"> View</a>

                                <a class="btn btn-success btn-sm active" href="{{url('admin/users/'. $row->id .'/edit')}}"> Edit</a>


                                <label class="btn btn-danger btn-sm">
                                <input type="radio" name="options" id="option3" autocomplete="off"> Delete
                                </label>
                            </div>

                        </td>
                </tr>
                @endforeach

            </tbody>
            <tfoot>
            <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>User Type</th>
            <th>Action</th>
            </tr>
            </tfoot>
        </table>
        </div>
        <!-- /.card-body -->
    </div>

@endsection

@push('js')
  <!-- DataTables -->
    <script src="{{asset('backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('backend/dist/js/adminlte.min.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{asset('backend/dist/js/demo.js')}}"></script>
    <!-- page script -->
    <script>
    $(function () {
        $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
        });
        $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
        });
    });
    </script>

@endpush

resources/views/admin/users/view.blade.php
@extends('layouts.admin')
@section('title',$User->name)
@push('css')
    <link rel="stylesheet" href="{{asset('backend/plugins/daterangepicker/daterangepicker.css')}}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="{{asset('backend/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css')}}">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{asset('backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('backend/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="{{asset('backend/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('backend/dist/css/adminlte.min.css')}}">

@endpush


@section('content')
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">User Information</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form">

            <div class="row">
                <div class="col-md-8">
                    <div class="card-body">

                        <div class="form-group">
                            <label for="full_name">Khmer Name</label>
                            <input type="text" class="form-control" id="full_name" placeholder="Enter Full Name" value="{{$User->name}}">
                        </div>

                        <div class="form-group">
                            <label for="full_name">Latin Name</label>
                            <input type="text" class="form-control" id="full_name" placeholder="Enter Full Name" value="{{$User->latin_name}}">
                        </div>

                        <div class="form-group">
                            <label for="full_name">Gender</label>
                            <select class="custom-select">
                                <option {{$User->gender=='M'?'selected':''}} value="M">Male</option>
                                <option {{$User->gender=='F'?'selected':''}} value="F">Female</option>

                            </select>
                        </div>

                        <div class="form-group">
                          <label for="exampleInputEmail1">Email address</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" value="{{$User->email}}">
                        </div>



                    </div>

                </div>
                <div class="col-md 4">
                    @php
                    $Profile=$User->photo!=NULL?$User->photo:'users/default.jpg';
                @endphp

                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                          <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src="{{asset('uploads/'.$Profile)}}" alt="User profile picture">
                          </div>

                          <h3 class="profile-username text-center">{{$User->name}}</h3>

                          <p class="text-muted text-center">{{$User->user_type}}</p>

                          <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                              <b>Followers</b> <a class="float-right">1,322</a>
                            </li>
                            <li class="list-group-item">
                              <b>Following</b> <a class="float-right">543</a>
                            </li>
                            <li class="list-group-item">
                              <b>Friends</b> <a class="float-right">13,287</a>
                            </li>
                          </ul>

                          <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
                        </div>
                        <!-- /.card-body -->
                      </div>
                </div>



            </div>




      <!-- /.card-body -->

      <div class="card-footer">

        <a  class="btn btn-primary" href="{{url('admin/users')}}">Back</a>
      </div>
    </form>
  </div>

@endsection

@push('js')

<!-- Bootstrap 4 -->
<script src="{{asset('backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- Select2 -->
<script src="{{asset('backend/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{{asset('backend/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js')}}"></script>
<!-- InputMask -->
<script src="{{asset('backend/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('backend/plugins/inputmask/min/jquery.inputmask.bundle.min.js')}}"></script>
<!-- date-range-picker -->
<script src="{{asset('backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- bootstrap color picker -->
<script src="{{asset('backend/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Bootstrap Switch -->
<script src="{{asset('backend/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('backend/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('backend/dist/js/demo.js')}}"></script>
<!-- Page script -->
<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
        theme: 'bootstrap4'
        })

        //Datemask dd/mm/yyyy
        $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
        //Datemask2 mm/dd/yyyy
        $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
        //Money Euro
        $('[data-mask]').inputmask()

        //Date range picker
        $('#reservation').daterangepicker()
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({
        timePicker: true,
        timePickerIncrement: 30,
        locale: {
            format: 'MM/DD/YYYY hh:mm A'
        }
        })
        //Date range as a button
        $('#daterange-btn').daterangepicker(
        {
            ranges   : {
            'Today'       : [moment(), moment()],
            'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month'  : [moment().startOf('month'), moment().endOf('month')],
            'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            startDate: moment().subtract(29, 'days'),
            endDate  : moment()
        },
        function (start, end) {
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
        }
        )

        //Timepicker
        $('#timepicker').datetimepicker({
        format: 'LT'
        })

        //Bootstrap Duallistbox
        $('.duallistbox').bootstrapDualListbox()

        //Colorpicker
        $('.my-colorpicker1').colorpicker()
        //color picker with addon
        $('.my-colorpicker2').colorpicker()

        $('.my-colorpicker2').on('colorpickerChange', function(event) {
        $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
        });

        $("input[data-bootstrap-switch]").each(function(){
        $(this).bootstrapSwitch('state', $(this).prop('checked'));
        });

    })
    </script>
@endpush